name: Run Test

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '0 0 * * *'
    
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        default: Staging
      kreversion:
        description: 'KRE Version'
        required: true
        default: 8.6.6
        type: choice
        options:
          - 8.6.8
          - 8.6.6
          - 8.6.5
      testsuite:
        description: 'Testsuite'
        required: true
        default: Fast Test 1
        type: choice
        options:
          - Fast Test 2
          - Fast Test 3
      runner:
        description: 'Runner'
        required: true
        default: windows-latest
        type: choice
        options:
          - windows-latest
          - windows-2019
          - macos-13
          - macos-latest
          - macos-11
          - ubuntu-latest
          - ubuntu-20.04
      browser:
        description: 'Browser'
        required: true
        default: Chrome
        type: choice
        options:
          - Chrome
          - Firefox
          - IE
          - Safari
          - Edge
          - Edge Chromium
      slacknotify:
        description: 'Send slack notification'
        required: true
        default: true
        type: boolean

jobs:
  test_schedule:
    runs-on: windows-latest
    steps:
      - name: Testing name
        run: echo "This is a test created by TONY"
