name: Run Test

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '0 0 * * *'
    
  workflow_dispatch:
    inputs:
      kreversion:
        description: 'KRE Version'
        required: true
        default: 8.6.6
        type: choice
        options:
          - 8.6.8
          - 8.6.6
          - 8.6.5
      testsuite:
        description: 'Testsuite'
        required: true
        default: Test Suites/Fast Test by Tony/Admin Profile
        type: choice
        options:
          - Test Suites/Fast Test by Tony/Admin Profile
          - APIs Test
          - Fast Test
          - Story Test
          - Feature Test
          - P1 Test
          - P2 Test
          - P3 Test
      runner:
        description: 'Runner'
        required: true
        default: windows-latest
        type: choice
        options:
          - windows-latest
          - windows-2019
          - macos-13
          - macos-latest
          - macos-11
          - ubuntu-latest
          - ubuntu-20.04
      browser:
        description: 'Browser'
        required: true
        default: Chrome
        type: choice
        options:
          - Chrome
          - Firefox
          - IE
          - Safari
          - Edge
          - Edge Chromium
      slacknotify:
        description: 'Send slack notification'
        required: true
        default: true
        type: boolean
      one:
        description: 'ONE'
        default: true
        type: choice

jobs:
  test_schedule:
    runs-on: windows-latest
    steps:
      - name: Testing name
        run: echo "This is a test created by TONY"
