name: Run Test

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '0 0 * * *'
    
  workflow_dispatch:
    inputs:
      kreversion:
        description: 'KRE Version'
        required: true
        default: 8.6.6
        type: choice
        options:
          - 8.6.8
          - 8.6.6
          - 8.6.5
      testsuite:
        description: 'Test Suite'
        required: true
        default: Fast Test Demo
        type: choice
        options:
          - Fast Test Demo
          - Fast Test 1
          - Fast Test 2
      runner:
        description: 'Runner'
        required: true
        default: windows-latest
        type: choice
        options:
          - windows-latest
          - windows-2019
          - macos-13
          - macos-latest
          - macos-11
          - ubuntu-latest
          - ubuntu-20.04
      browser:
        description: 'Browser'
        required: true
        default: Chrome
        type: choice
        options:
          - Chrome
          - Firefox
          - IE
          - Safari
          - Edge
          - Edge Chromium
      slacknotify:
        description: 'Send slack notification'
        required: true
        default: true
        type: boolean

jobs:
  auto:
    name: Execute test when push
    if: ${{ github.event.inputs.browser == '' && github.event_name == 'push' }}
    runs-on: windows-latest
    strategy:
      matrix:
        os-runner: ['Chrome', 'Firefox', 'Safari']
    steps:
    - run: |
        echo "This is a test created by TONY"
        echo ${{ matrix.os-runner }}
  manual:
    name: Execute test by manual trigger
    if: ${{ github.event.inputs.browser !='' }}
    runs-on: ${{ github.event.inputs.runner }}
    steps:
    - run: echo ${{ github.event.inputs.runner }}
  sendnote:
    name: Send note
    if: ${{ always() }}
    needs: [auto, manual]
    runs-on: windows-latest
    steps:
    - run: echo "sendnote test"
     
