name: Run Regression Test by Manual trigger

on:
  pull_request:
    branches: 
      - 'main'
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 0 * * *'
    
  workflow_dispatch:
    inputs:
      kreversion:
        description: 'KRE Version'
        required: true
        default: 8.6.6
        type: choice
        options:
          - 8.6.8
          - 8.6.6
          - 8.6.5
      profile:
        description: 'Execution Profile'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
          - qa
      testsuite:
        description: 'Test Suite'
        required: true
        default: Staging Regression Test - Admin
        type: choice
        options:
          - Staging Regression Test - Admin
          - Production Regression Test - Admin
      runner:
        description: 'Runner'
        required: true
        default: windows-latest
        type: choice
        options:
          - windows-latest
          - windows-2019
          - macos-13
          - macos-latest
          - macos-11
          - ubuntu-latest
          - ubuntu-20.04
      browser:
        description: 'Browser'
        required: true
        default: Chrome
        type: choice
        options:
          - Chrome
          - Firefox
          - IE
          - Safari
          - Edge
          - Edge Chromium
      slacknotify:
        description: 'Send slack notification'
        required: true
        default: true
        type: boolean

jobs:
  manual:
    name: Execute test by manual trigger
    if: ${{ github.event.inputs.browser !='' }}
    runs-on: ${{ github.event.inputs.runner }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Execute test
      id: execute-test-manual
      uses: katalon-studio/katalon-studio-github-action@v3.0
      with:
          version: ${{ github.event.inputs.kreversion }}
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -testSuitePath="Test Suites/Fast Test/${{ github.event.inputs.testsuite }}" -browserType= ${{ github.event.inputs.browser }} -executionProfile=${{ github.event.inputs.profile }} -apiKey= ${{ secrets.API_KEY }} -orgID=${{ secrets.ORG_ID }} -testOpsProjectId=${{ secrets.PROJECT_ID }} --config -webui.autoUpdateDrivers=true'         
      env:
       BROWSER: ${{ github.event.inputs.browser }}
